site_name: CodeLink
site_url: https://hbcodelink.github.io/CodeLink-docs/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch

plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
