site_name: CodeLink
site_url: https://hbcodelink.github.io/CodeLink-docs/
nav:
  - Home: index.md
  - October:
      - October/lesson0.md
      - October/lesson1.md
      - October/lesson2.md
      - October/lesson3.md
      - October/lesson4.md
  - November:
      - November/lesson1.md
      - November/lesson2.md
      - November/lesson3.md
      - November/lesson4.md
  - December:
      - December/resources.md
  - April: April/lesson1.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.instant.prefetch
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch
      primary: green
      accent: black
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light
      primary: green
      accent: purple

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - footnotes
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HBCodeLink
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/hb_codelink
copyright: |
  &copy; 2024 <a href="https://github.com/HBCodeLink" target="_blank" rel="noopener">CodeLink</a>
